org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:-TieredCompilation
android.useAndroidX=true
android.enableJetifier=true
# 国内镜像加速
systemProp.gradle.internal.repository.proxy=https://mirrors.cloud.tencent.com/gradle/
org.gradle.jvmargs=-Xmx4G
