'use client';
import { useTheme } from '@/contexts/ThemeContext';
import { useColorTheme } from '@/contexts/ColorThemeContext';
import { colorThemes, type ColorThemeId } from '@/lib/color-themes';
import { Check, Monitor, Moon, Sun } from 'lucide-react';
import { useI18n } from '@/contexts/I18nContext';
const LABEL: Record<ColorThemeId,string> = { emerald:'appearance.colorEmerald',ocean:'appearance.colorOcean',sunset:'appearance.colorSunset',lavender:'appearance.colorLavender',rose:'appearance.colorRose',graphite:'appearance.colorGraphite' };
export function AppearancePanel() {
 const { t, localeTag } = useI18n(); const zh=localeTag==='zh_CN'; const { theme,setTheme }=useTheme(); const { colorThemeId,setColorTheme }=useColorTheme();
 return <div className="space-y-8"><section><h2 className="mb-4 text-sm font-medium">{zh?'显示模式':'Display mode'}</h2><div className="grid grid-cols-3 gap-3">{(['light','dark','system'] as const).map(mode=>{const Icon=mode==='light'?Sun:mode==='dark'?Moon:Monitor;return <button key={mode} type="button" aria-pressed={theme===mode} onClick={()=>setTheme(mode)} className={`flex min-h-32 flex-col items-center justify-center gap-4 rounded-xl border p-4 text-sm transition-colors ${theme===mode?'border-primary bg-accent-soft text-primary':'border-border hover:bg-muted'}`}><Icon size={28} strokeWidth={1.5}/><span className="flex items-center gap-1.5">{t(mode==='light'?'appearance.themeLight':mode==='dark'?'appearance.themeDark':'appearance.themeSystem')}{theme===mode&&<Check size={14}/>}</span></button>;})}</div></section><section className="border-t border-border pt-6"><h2 className="mb-1 text-sm font-medium">{zh?'主题颜色':'Accent color'}</h2><p className="mb-5 text-xs text-muted-foreground">{zh?'用于按钮、选中状态和发送的消息。':'Used for buttons, selected items and your messages.'}</p><div className="flex flex-wrap gap-2 sm:gap-5">{colorThemes.map(ct=><button key={ct.id} onClick={()=>setColorTheme(ct.id)} aria-pressed={colorThemeId===ct.id} className="flex min-h-16 min-w-12 flex-col items-center gap-2 text-xs"><span className="flex size-9 items-center justify-center rounded-full ring-offset-4 ring-offset-card" style={{backgroundColor:ct.accent,outline:colorThemeId===ct.id?`2px solid ${ct.accent}`:undefined,outlineOffset:3}}>{colorThemeId===ct.id&&<Check size={16} className="text-white"/>}</span><span className="text-muted-foreground">{t(LABEL[ct.id])}</span></button>)}</div></section></div>;
}
