'use client';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Cloud, Download, Ellipsis, Folder, FolderPlus, Pencil, Plus, RefreshCw, Search, Trash2, Upload } from 'lucide-react';
import { useI18n } from '@/contexts/I18nContext';
import { FilesShell } from './FilesShell';
import { FilePreviewDialog } from './FilePreviewDialog';
import { CloudTransferList } from './CloudTransferList';
import { startCloudTransfer } from '@/lib/cloudTransfers';
import { PageHeader, EmptyState } from '@/components/ui/page';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { FileIcon } from '@/components/FileIcon';
import { formatFileSize,getFileCategory } from '@/lib/fileUtils';
import { previewDav,readDavConnections,saveDavConnection,removeDavConnection,setDavPassword,davNeedsPassword,listDav,downloadDav,uploadDav,createDavFolder,renameDavEntry,deleteDavEntry,davError,type DavConnection,type DavEntry } from '@/lib/webdav';

export function CloudWorkspace({ connectionsOnly=false }: { connectionsOnly?: boolean }) {
 const { localeTag }=useI18n();const zh=localeTag==='zh_CN';
 const [connections,setConnections]=useState<DavConnection[]>([]);const [connection,setConnection]=useState<DavConnection|null>(null);const [path,setPath]=useState('');const [entries,setEntries]=useState<DavEntry[]>([]);
 const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [query,setQuery]=useState('');const [editor,setEditor]=useState(false);const [editingId,setEditingId]=useState<string|null>(null);
 const [name,setName]=useState('');const [url,setUrl]=useState('');const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [unlock,setUnlock]=useState<DavConnection|null>(null);
 const [action,setAction]=useState<'folder'|'rename'|'delete'|'remove'|null>(null);const [target,setTarget]=useState<DavEntry|null>(null);const [nextName,setNextName]=useState('');
 const picker=useRef<HTMLInputElement>(null);const requestId=useRef(0);const [details,setDetails]=useState<DavEntry|null>(null);const [preview,setPreview]=useState<File|null>(null);const [previewing,setPreviewing]=useState(false);
 useEffect(()=>{setConnections(readDavConnections());const request=requestId;return () => { request.current++; };},[]);
 const refresh=useCallback(async(c:DavConnection,p:string)=>{const id=++requestId.current;setLoading(true);setError('');try{const next=await listDav(c,p);if(id===requestId.current)setEntries(next);}catch(e){if(id===requestId.current)setError(davError(e,zh));}finally{if(id===requestId.current)setLoading(false);}},[zh]);
 useEffect(()=>{const handler=(event:Event)=>{const changed=(event as CustomEvent<{id:string;path:string}>).detail;if(connection && changed.id===connection.id && changed.path===path)void refresh(connection,path);};window.addEventListener('shrimpsend:dav-changed',handler);return()=>window.removeEventListener('shrimpsend:dav-changed',handler);},[connection,path,refresh]);
 const open=(c:DavConnection,p=c.url)=>{if(davNeedsPassword(c)){setPassword('');setUnlock(c);return;}setConnection(c);setPath(p);setEntries([]);void refresh(c,p);};
 const edit=(c?:DavConnection)=>{setEditingId(c?.id || null);setName(c?.name || '');setUrl(c?.url || '');setUsername(c?.username || '');setPassword('');setError('');setEditor(true);};
 const perform=async(work:()=>Promise<void>)=>{setLoading(true);setError('');try{await work();setAction(null);if(connection && action !== 'remove')await refresh(connection,path);}catch(e){setError(davError(e,zh));}finally{setLoading(false);}};
 const shown=entries.filter(e=>e.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <FilesShell><PageHeader title={connectionsOnly?(zh?'连接设置':'Connections'):(zh?'云端文件':'Cloud files')} description={zh?'连接自己的存储服务，文件始终由你掌握。':'Connect your own storage and keep control of your files.'} actions={<Button onClick={()=>edit()}><Plus size={16}/>{zh?'添加连接':'Add connection'}</Button>}/>
 <CloudTransferList/>
 {error&&<p role="alert" className="quiet-note mb-5">{error}</p>}
 {(!connection || connectionsOnly)?<><div className="space-y-3">{connections.map(c=><article key={c.id} className="flex flex-wrap items-center gap-4 rounded-xl border border-border p-5"><Cloud size={28} strokeWidth={1.4} className="text-primary"/><div className="min-w-0 flex-1"><h2 className="text-sm font-medium">{c.name}</h2><p className="mt-1 truncate text-xs text-muted-foreground">{c.url}</p></div><Button variant="ghost" size="icon" aria-label={zh?'编辑连接':'Edit connection'} onClick={()=>edit(c)}><Pencil size={16}/></Button><Button variant="outline" onClick={()=>{if(connectionsOnly){setConnection(c);setAction('remove');}else open(c);}}>{connectionsOnly?(zh?'移除':'Remove'):(zh?'打开':'Open')}</Button></article>)}</div>{!connections.length&&<EmptyState icon={Cloud} title={zh?'连接你的云端文件':'Connect your cloud files'} description={zh?'添加 WebDAV 存储，即可浏览、下载和上传文件。':'Add WebDAV storage to browse, download and upload files.'} action={<Button variant="outline" onClick={()=>edit()}>{zh?'添加 WebDAV 连接':'Add WebDAV connection'}</Button>}/>}<section className="mt-8 border-t border-border pt-5"><Link href="/settings/s3" className="flex items-center gap-3 text-sm hover:text-primary"><Cloud size={18}/>{zh?'S3 备用中转设置 →':'S3 relay settings →'}</Link><p className="mt-3 text-xs leading-6 text-muted-foreground">{zh?'WebDAV 密码仅在当前页面会话中使用。浏览器访问需要存储服务允许跨域请求；桌面端不受此浏览器限制。':'WebDAV passwords remain in this page session. Browser access requires the storage server to allow cross-origin requests. Desktop clients do not have this browser limitation.'}</p></section></>:<>
 <div className="mb-5 flex flex-wrap items-center gap-2 text-sm"><Button variant="ghost" onClick={()=>{requestId.current++;setConnection(null);setEntries([]);}}>{zh?'所有连接':'All connections'}</Button><span className="text-muted-foreground">/</span><Button variant="ghost" onClick={()=>open(connection)}>{connection.name}</Button>{decodeURIComponent(new URL(path).pathname.slice(new URL(connection.url).pathname.length)).split('/').filter(Boolean).map((part,i,all)=><span key={i} className="flex items-center gap-2"><span className="text-muted-foreground">/</span><Button variant="ghost" onClick={()=>open(connection,new URL(all.slice(0,i+1).map(encodeURIComponent).join('/')+'/',connection.url).href)}>{part}</Button></span>)}</div>
 <div className="mb-5 flex flex-wrap justify-between gap-3"><div className="flex gap-2"><Button variant="outline" disabled={loading} onClick={()=>picker.current?.click()}><Upload size={16}/>{zh?'上传':'Upload'}</Button><Button variant="outline" onClick={()=>{setNextName('');setAction('folder');}}><FolderPlus size={16}/>{zh?'新建文件夹':'New folder'}</Button><Button variant="ghost" size="icon" aria-label={zh?'刷新':'Refresh'} disabled={loading} onClick={()=>void refresh(connection,path)}><RefreshCw size={17} className={loading?'animate-spin':''}/></Button></div><div className="relative"><Search size={16} className="absolute left-3 top-3 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={zh?'搜索当前文件夹':'Search this folder'} aria-label={zh?'搜索当前文件夹':'Search this folder'} className="pl-9"/></div></div>
 <input type="file" ref={picker} className="hidden" multiple onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;void startCloudTransfer(zh?`上传 ${files.length} 个文件`:`Upload ${files.length} files`,async (signal,progress)=>{for(let i=0;i<files.length;i++){await uploadDav(connection,path,files[i],signal);progress((i+1)/files.length*100);}window.dispatchEvent(new CustomEvent('shrimpsend:dav-changed',{detail:{id:connection.id,path}}));});}}/>
 {loading&&!entries.length?<p role="status" className="py-12 text-center text-sm text-muted-foreground">{zh?'正在读取文件…':'Loading files…'}</p>:!shown.length?<EmptyState icon={Folder} title={query?(zh?'没有匹配文件':'No matching files'):(zh?'空文件夹':'Empty folder')}/>:<div className="overflow-x-auto"><table className="product-table cloud-files-table"><thead><tr><th>{zh?'名称':'Name'}</th><th>{zh?'大小':'Size'}</th><th className="max-lg:hidden">{zh?'修改时间':'Modified'}</th><th><span className="sr-only">{zh?'操作':'Actions'}</span></th></tr></thead><tbody>{shown.map(entry=><tr key={entry.path}><td><button className="flex max-w-72 items-center gap-3 text-left" onClick={()=>{if(entry.directory)open(connection,entry.path);else setDetails(entry);}}>{entry.directory?<Folder size={26} className="text-primary"/>:<FileIcon size={28} category={getFileCategory(entry.name)}/>}<span className="truncate">{entry.name}</span></button></td><td className="whitespace-nowrap text-muted-foreground">{entry.directory?'—':formatFileSize(entry.size)}</td><td className="text-xs text-muted-foreground max-lg:hidden">{entry.modified?new Date(entry.modified).toLocaleDateString():'—'}</td><td><Button variant="ghost" size="icon" className="sm:hidden" aria-label={`${zh?'管理':'Manage'} ${entry.name}`} onClick={()=>setDetails(entry)}><Ellipsis size={18}/></Button><div className="hidden justify-end sm:flex">{!entry.directory&&<Button variant="ghost" size="icon" aria-label={`${zh?'下载':'Download'} ${entry.name}`} onClick={()=>void startCloudTransfer(entry.name,(signal,progress)=>downloadDav(connection,entry,progress,signal))}><Download size={16}/></Button>}<Button variant="ghost" size="icon" aria-label={`${zh?'重命名':'Rename'} ${entry.name}`} onClick={()=>{setTarget(entry);setNextName(entry.name);setAction('rename');}}><Pencil size={16}/></Button><Button variant="ghost" size="icon" aria-label={`${zh?'删除':'Delete'} ${entry.name}`} onClick={()=>{setTarget(entry);setAction('delete');}}><Trash2 size={16}/></Button></div></td></tr>)}</tbody></table></div>}
 </>}
 <FilePreviewDialog file={preview} onClose={()=>setPreview(null)}/>
 <Dialog open={!!details} onOpenChange={open=>{if(!open)setDetails(null);}}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle className="break-all">{details?.name}</DialogTitle></DialogHeader>{details&&<><div className="flex justify-center rounded-lg bg-muted py-10"><FileIcon size={48} category={getFileCategory(details.name)}/></div><dl className="grid grid-cols-2 gap-3 text-sm"><dt>{zh?'大小':'Size'}</dt><dd>{formatFileSize(details.size)}</dd><dt>{zh?'修改时间':'Modified'}</dt><dd>{details.modified?new Date(details.modified).toLocaleString():'—'}</dd></dl>{!details.directory && details.size <= 32 * 1024 * 1024 && <Button variant="outline" disabled={previewing} onClick={async()=>{if(!connection)return;setPreviewing(true);try{setPreview(await previewDav(connection,details));setDetails(null);}catch(e){setError(davError(e,zh));}finally{setPreviewing(false);}}}>{previewing?(zh?'正在打开…':'Opening…'):(zh?'预览内容':'Preview')}</Button>}{error && <p role="alert" className="text-xs text-destructive">{error}</p>}{!details.directory && <Button onClick={()=>{if(connection)startCloudTransfer(details.name,(signal,progress)=>downloadDav(connection,details,progress,signal));setDetails(null);}}><Download size={16}/>{zh?'下载到接收文件夹':'Download to receive folder'}</Button>}<div className="flex gap-2 border-t pt-4"><Button variant="outline" onClick={()=>{setTarget(details);setNextName(details.name);setAction('rename');setDetails(null);}}>{zh?'重命名':'Rename'}</Button><Button variant="ghost" className="text-destructive" onClick={()=>{setTarget(details);setAction('delete');setDetails(null);}}>{zh?'删除':'Delete'}</Button></div></>}</DialogContent></Dialog>
 <Dialog open={editor} onOpenChange={setEditor}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>{editingId?(zh?'编辑连接':'Edit connection'):(zh?'添加 WebDAV':'Add WebDAV')}</DialogTitle><DialogDescription>{zh?'填写存储服务提供的连接信息。':'Use the connection details from your storage provider.'}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={async e=>{e.preventDefault();setLoading(true);setError('');try{const c=saveDavConnection({id:editingId || crypto.randomUUID(),name:name.trim(),url,username},editingId && !password ? undefined : password);setConnections(readDavConnections());setEditor(false);if(!connectionsOnly)open(c);}catch(e){setError(davError(e,zh));}finally{setLoading(false);}}}>{[[zh?'名称':'Name',name,setName,'text'],[zh?'服务地址':'Server URL',url,setUrl,'url'],[zh?'用户名':'Username',username,setUsername,'text'],[zh?'密码':'Password',password,setPassword,'password']].map(([label,value,set,type],i)=><label key={i} className="block space-y-2 text-xs"><span>{label as string}</span><Input type={type as string} value={value as string} onChange={e=>(set as (v:string)=>void)(e.target.value)} required={i<2} autoComplete={i===3?'current-password':'off'} placeholder={i===1?'https://cloud.example.com/dav/':undefined}/></label>)}{error&&<p role="alert" className="text-xs text-destructive">{error}</p>}<Button type="submit" className="w-full" disabled={loading||!name.trim()||!url.trim()}>{zh?'保存连接':'Save connection'}</Button></form></DialogContent></Dialog>
 <Dialog open={!!unlock} onOpenChange={open=>{if(!open)setUnlock(null);}}><DialogContent className="sm:max-w-sm"><DialogHeader><DialogTitle>{zh?'连接密码':'Connection password'}</DialogTitle><DialogDescription>{unlock?.name}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e=>{e.preventDefault();if(unlock){setDavPassword(unlock.id,password);open(unlock);setUnlock(null);}}}><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} aria-label={zh?'密码':'Password'} autoComplete="current-password"/><Button type="submit" className="w-full">{zh?'连接':'Connect'}</Button></form></DialogContent></Dialog>
 <Dialog open={!!action} onOpenChange={open=>{if(!open)setAction(null);}}><DialogContent className="sm:max-w-sm"><DialogHeader><DialogTitle>{action==='folder'?(zh?'新建文件夹':'New folder'):action==='rename'?(zh?'重命名':'Rename'):action==='remove'?(zh?'移除连接？':'Remove connection?'):(zh?'删除这个项目？':'Delete this item?')}</DialogTitle><DialogDescription>{action==='delete'?(zh?'文件会从云端删除，此操作无法撤销。':'This permanently deletes the item from cloud storage.'):action==='remove'?(zh?'只移除本机的连接设置，云端文件保留。':'Only removes this connection. Cloud files are kept.'):target?.name || connection?.name}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e=>{e.preventDefault();if(!connection)return;void perform(async()=>{if(action==='folder')await createDavFolder(connection,path,nextName);if(action==='rename'&&target)await renameDavEntry(connection,target,nextName);if(action==='delete'&&target)await deleteDavEntry(connection,target);if(action==='remove'){requestId.current++;removeDavConnection(connection.id);setConnections(readDavConnections());setConnection(null);}});}}>{(action==='folder'||action==='rename')&&<Input aria-label={zh?'名称':'Name'} value={nextName} onChange={e=>setNextName(e.target.value)} autoFocus/>}{error&&<p role="alert" className="text-xs text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" type="button" onClick={()=>setAction(null)}>{zh?'取消':'Cancel'}</Button><Button type="submit" variant={action==='delete'?'destructive':'default'} disabled={loading||((action==='folder'||action==='rename')&&!nextName.trim())}>{zh?'确认':'Confirm'}</Button></div></form></DialogContent></Dialog>
 </FilesShell>;
}
